#ifndef INITIALIZER_MNISTLOGICINITIALIZER_H_
#define INITIALIZER_MNISTLOGICINITIALIZER_H_

#include "BlackBoxInitializer.h"
#include "../problems/MnistLogicProblem.h"
#include "../functions/BooleanFunctions.h"

#include <fstream>
#include <sstream>
#include <stdexcept>
#include <iostream>

template<class E, class G, class F>
class MnistLogicInitializer : public BlackBoxInitializer<E, G, F> {
public:
    // Parameter for number of bits per class (e.g., 50)
    // Total output = 10 classes * 50 bits = 500
    const int BITS_PER_CLASS = 50; 

    MnistLogicInitializer(const std::string &p_benchmark_file)
        : BlackBoxInitializer<E, G, F>(p_benchmark_file) {
    }

    std::vector<std::vector<E>> full_inputs_store;
    std::vector<std::vector<E>> full_outputs_store;

    ~MnistLogicInitializer() = default;

    /**
     * @brief Reads the mnist_boolean.txt file generated by Python.
     * File format:
     * Header: NUM_SAMPLES NUM_INPUTS NUM_CLASSES
     * Rows: LABEL pixel1 pixel2 ... pixel784
     */
    void read_data() override {
        std::ifstream ifs(this->benchmark_file);

        std::cout << "[DEBUG] Batch Training Enabled? " << (this->parameters->get_batch_training() > 0 ? "YES" : "NO") << std::endl;
        std::cout << "[DEBUG] Batch Size Param: " << this->parameters->get_batch_size() << std::endl;
        std::cout << "[DEBUG] File Size Param: " << this->parameters->get_file_size() << std::endl;
        
        if (!ifs.is_open()) {
            throw std::runtime_error("Could not open MNIST data file: " + this->benchmark_file);
        }

        int num_samples_file, num_inputs_file, num_classes_file;
        
        // 1. Read the header
        if (!(ifs >> num_samples_file >> num_inputs_file >> num_classes_file)) {
            throw std::runtime_error("Error reading MNIST header!");
        }

        std::cout << "Loading MNIST Data..." << std::endl;
        std::cout << "Samples in file: " << num_samples_file 
                  << ", Inputs: " << num_inputs_file 
                  << ", Classes: " << num_classes_file << std::endl;

        // [FIX CRITICO] Separiamo quante righe leggere (TUTTE) da quante usarne attivamente (BATCH)
        int total_samples_to_read = num_samples_file;

        if (this->parameters->get_batch_training() > 0) {
            // Se usiamo batch training, l'istanza attiva avrà dimensione ridotta (es. 200)
            this->num_instances = this->parameters->get_batch_size();
            
            // Check di coerenza opzionale
            if (num_samples_file != this->parameters->get_file_size()) {
                std::cout << "WARNING: file_size in params (" << this->parameters->get_file_size() 
                          << ") differs from file header (" << num_samples_file << ")!" << std::endl;
            }
        } else {
            // Se no, usiamo tutto
            this->num_instances = num_samples_file;
        }
              
        this->parameters->set_num_variables(num_inputs_file); // 784
        
        // Total outputs = Classes * Bits per class (e.g. 10 * 50 = 500)
        int total_outputs = num_classes_file * BITS_PER_CLASS;
        this->parameters->set_num_outputs(total_outputs);

        // Allocates active input/output vectors (Questi conterranno solo la batch corrente)
        this->inputs = std::make_shared<std::vector<std::vector<E>>>();
        this->outputs = std::make_shared<std::vector<std::vector<E>>>();

        // Temporary storage for ALL data (Questo deve contenere TUTTO il file)
        std::vector<std::vector<E>> all_inputs_vec;
        std::vector<std::vector<E>> all_outputs_vec;

        // Pre-allocazione per performance
        all_inputs_vec.reserve(total_samples_to_read);
        all_outputs_vec.reserve(total_samples_to_read);

        // Read the rows (Label + Pixel)
        int label;
        E pixel_val;

        // [FIX] Usiamo total_samples_to_read (60000) invece di this->num_instances (200)
        for (int i = 0; i < total_samples_to_read; ++i) {
            // Read the Label (first column)
            if (!(ifs >> label)) {
                throw std::runtime_error("Error reading label at line " + std::to_string(i + 1));
            }

            std::vector<E> row_out;
            row_out.push_back(static_cast<E>(label));
            all_outputs_vec.push_back(row_out);

            //  Read the Pixels (subsequent columns)
            std::vector<E> row_in(num_inputs_file);
            for (int j = 0; j < num_inputs_file; ++j) {
                ifs >> pixel_val;
                row_in[j] = pixel_val;
            }
            all_inputs_vec.push_back(row_in);
        }

        std::cout << "MNIST Data Loaded Successfully. Read " << all_inputs_vec.size() << " samples." << std::endl;
        ifs.close();

        // Initialize the active vectors with the first batch ONLY
        // Qui usiamo this->num_instances (che è 200 nel caso batch)
        int active_size = this->num_instances; 
        for(int i=0; i<active_size; i++) {
            this->inputs->push_back(all_inputs_vec[i]);
            this->outputs->push_back(all_outputs_vec[i]);
        }

        // Store completo per i futuri switch
        this->full_inputs_store = all_inputs_vec;
        this->full_outputs_store = all_outputs_vec;
    }

    /**
     * @brief Initialize boolean functions.
     */
    void init_functions() override {
        this->functions = std::make_shared<FunctionsBoolean<E>>(this->parameters);
    }

    /**
     * @brief Initialize the MNIST Logic problem.
     */
    void init_problem() override {
        std::cout << "[DEBUG] MnistLogicInitializer::init_problem -> Start" << std::endl;

        int training_instances = this->num_instances;
        if (this->parameters->get_batch_training() > 0) {
            training_instances = this->parameters->get_batch_size();
        }
        
        // Verifica puntatori critici prima di usarli
        if (!this->evaluator) std::cerr << "[ERROR] Evaluator is NULL!" << std::endl;
        if (!this->inputs) std::cerr << "[ERROR] Inputs vector is NULL!" << std::endl;

        std::cout << "[DEBUG] Creating MnistLogicProblem instance..." << std::endl;
        auto mnist_problem = std::make_shared<MnistLogicProblem<E, G, F>>(
            this->parameters, 
            this->evaluator, 
            this->inputs,
            this->outputs, 
            this->constants, 
            training_instances
        );
        
        std::cout << "[DEBUG] Calling set_full_dataset (with std::move)..." << std::endl;
        // QUI usiamo std::move per trasferire la proprietà dei vettori senza copiarli
        mnist_problem->set_full_dataset(std::move(this->full_inputs_store), std::move(this->full_outputs_store));
        
        this->problem = mnist_problem;

        // we want to minimize the number of errors (maximize correct classifications)
        this->parameters->set_minimizing_fitness(true);

        if (this->parameters->get_ideal_fitness() == -1) {
             this->parameters->set_ideal_fitness(0.01);
        }

        std::cout << "[DEBUG] Registering problem in composite..." << std::endl;
        // REGISTRATION IN THE COMPOSITE
        this->composite->set_problem(this->problem);
        
        std::cout << "[DEBUG] MnistLogicInitializer::init_problem -> End" << std::endl;
    }
};

#endif /* INITIALIZER_MNISTLOGICINITIALIZER_H_ */